### ISSUE TITLE
Login redirects to Homepage

### ISSUE THREAD

**Issue by ak4zh** [engageintellect/spatz-2#12]
Just cloned the repo, added pocketbase url in .env and registered an account.
When I login it simply redirects me back to homepage with a toast that login successful but I am not logged in.

Something is wrong, not able to figure out what, I checked the login router `+page.server.ts` it looks ok.
I tried to console log in `hooks.server.ts` 
`pb.authStore.loadFromCookie(event.request.headers.get('cookie') || '')`
it returns null.

**Comment by ak4zh** [comment]
Figured I need to disable `secure` when setting the cookie in dev mode inside `hooks.server.ts`

`pb.authStore.exportToCookie({ httpOnly: false, secure: !dev })`

**Comment by engageintellect** [comment]
I know this was closed, but I just thought I would follow up just to make sure you got everything working smoothly?

If you would like to update the docs/readme to help other people avoid this issue, a PR would be appreciated.
