### ISSUE TITLE
any plans to update to pocketbase 0.23.x ?

### ISSUE THREAD

**Issue by insidesmart** [engageintellect/spatz-2#21]
Firstly, kudos for your efforts. looks like a nice starter project.

I have noticed that pocketbase 0.23.x versions have a different schema due to a recent rewrite with interesting features like otp for authentication, multi-factor auth, impersonation. 

just curious if you have plans to update to the latest pocketbase version ?

wish you good luck for your efforts.

**Comment by engageintellect** [comment]
I didn't realize that their was an update. I will check it out.

If you want to add it yourself and submit a PR - I'll merge it.

**Comment by engageintellect** [comment]
> Firstly, kudos for your efforts. looks like a nice starter project.
> 
> I have noticed that pocketbase 0.23.x versions have a different schema due to a recent rewrite with interesting features like otp for authentication, multi-factor auth, impersonation.
> 
> just curious if you have plans to update to the latest pocketbase version ?
> 
> wish you good luck for your efforts.

Updated, per your request. 🫡

Enjoy!

**Comment by insidesmart** [comment]
Thanks. Nicely done.
